-- Create user for WorksOn database
CREATE USER 'WorksOnQuery'@'%' IDENTIFIED BY 'Primary@Key53';
GRANT USAGE ON *.* TO 'WorksOnQuery'@'%' REQUIRE NONE WITH
    MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
GRANT SELECT ON `workson`.* TO 'WorksOnQuery'@'%';

-- Create user for Mondial database
CREATE USER 'MondialQuery'@'%' IDENTIFIED BY 'Referential&324';
GRANT USAGE ON *.* TO 'MondialQuery'@'%' REQUIRE NONE WITH
    MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
GRANT SELECT ON `mondial`.* TO 'MondialQuery'@'%';

-- Create user for WorksOn database
CREATE USER 'WorksOnDanger'@'%' IDENTIFIED BY 'Bunratty+44';
GRANT USAGE ON *.* TO 'WorksOnDanger'@'%' REQUIRE NONE WITH
    MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
GRANT SELECT, UPDATE, DELETE, INSERT, CREATE, DROP ON `workson`.* TO 'WorksOnDanger'@'%';
